language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn
before_script:
  - greenkeeper-lockfile-update
  - yarn lint
  - yarn lint:test
  - yarn test
script:
  - yarn build
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - yarn test:coveralls
