language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
  - npm run lint
  - npm run lint:test
  - npm test
script:
  - npm run build
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run test:coveralls
